### ISSUE TITLE
Seems like v0.13.0a3 broke async log listeners

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-python#155]
In edgedb/edgedb:

```
$ edb test -k test_server_proto_log_message_01

FAIL: test_server_proto_log_message_01 (test_server_proto.TestServerProto)


Traceback (most recent call last):
  File "/home/elvis/dev/edgedb/edgedb/edb/testbase/server.py", line 123, in wrapper
    self.loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/elvis/dev/edgedb/edgedb/tests/test_server_proto.py", line 801, in test_server_proto_log_message_01
    raise AssertionError('a notice message was not delivered')
AssertionError: a notice message was not delivered
```

**Comment by tailhook** [comment]
Fixed by #157
