### ISSUE TITLE
ValueError: 'edgedb/pgproto/pgproto.pyx' doesn't match any files

### ISSUE THREAD

**Issue by dmgolembiowski** [edgedb/edgedb-python#179]
### Reproduction steps:
```sh
$ pyenv install 3.9-dev
$ git clone https://github.com/edgedb/edgedb-python
$ pyenv local 3.9-dev; pyenv shell
$ # Update pip and install wheel ...
$ cd edgedb-python
$ pip install -e . 
```
results in ...
```sh
Obtaining file:///home/edgemorph/edgemorph/edm/bootstrap/edgedb-python
    ERROR: Command errored out with exit status 1:
    (... snip ...)
      File "/home/edgemorph/edgemorph/edm/bootstrap/edgedb-python/setup.py", line 252, in finalize_options
        self.distribution.ext_modules[:] = cythonize(
      File "/home/edgemorph/edgemorph/edm/bootstrap/edgedb-python/.eggs/Cython-0.29.14-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 959, in cytho
nize
        module_list, module_metadata = create_extension_list(
      File "/home/edgemorph/edgemorph/edm/bootstrap/edgedb-python/.eggs/Cython-0.29.14-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 810, in creat
e_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/edgemorph/edgemorph/edm/bootstrap/edgedb-python/.eggs/Cython-0.29.14-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 109, in nonem
pty
        raise ValueError(error_msg)
    ValueError: 'edgedb/pgproto/pgproto.pyx' doesn't match any files
    ----------------------------------------
WARNING: Discarding file:///home/edgemorph/edgemorph/edm/bootstrap/edgedb-python. Command errored out with exit status 1: python setup.py egg_info Check the lo
gs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
and as you'd probably expect:
```sh
$ python setup.py egg_info
running egg_info
creating edgedb.egg-info
writing edgedb.egg-info/PKG-INFO
writing dependency_links to edgedb.egg-info/dependency_links.txt
writing requirements to edgedb.egg-info/requires.txt
writing top-level names to edgedb.egg-info/top_level.txt
writing manifest file 'edgedb.egg-info/SOURCES.txt'
Traceback (most recent call last):
  File "/home/edgemorph/edgemorph/edm/bootstrap/edgedb-python/setup.py", line 278, in <module>
    (... snip ...)
ValueError: 'edgedb/pgproto/pgproto.pyx' doesn't match any files
```

Am I missing something?

**Comment by dmgolembiowski** [comment]
My apologies, I see the issue. Earlier when I had ran `git submodule init` as part of an external process, I believe I hadn't recursively cloned into postgres.

**Comment by 1st1** [comment]
NP!
