### ISSUE TITLE
Test fail when running locally

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb-python#42]
```
                                                                         
========================================================================== FAILURES ==========================================================================
________________________________________________________ TestProto.test_proto_codec_error_recovery_01 ________________________________________________________
Traceback (most recent call last):                                                                                                                            
  File "/work/tests/test_proto.py", line 36, in test_proto_codec_error_recovery_01                                                                            
    self.con.fetchall("SELECT <local_date>'0001-01-01 BC';")                   
  File "/work/edgedb/blocking_con.py", line 42, in fetchall                                                                                                   
    query, args, kwargs)                                                       
  File "edgedb/protocol/blocking_proto.pyx", line 74, in edgedb.protocol.blocking_proto.BlockingIOProtocol.sync_execute_anonymous                             
    return self._iter_coroutine(self.execute_anonymous(*args, **kwargs))                                                                                      
  File "edgedb/protocol/blocking_proto.pyx", line 60, in edgedb.protocol.blocking_proto.BlockingIOProtocol._iter_coroutine                                    
    coro.send(None)                                                                                                                                           
  File "edgedb/protocol/protocol.pyx", line 482, in execute_anonymous                                                                                         
    ret = await self._execute(in_dc, out_dc, args, kwargs)                                                                                                    
  File "edgedb/protocol/protocol.pyx", line 307, in _execute                                                                                                  
    raise exc                                                                                                                                                 edgedb.errors.InvalidValueError: invalid input syntax for type std::local_date: '0001-01-01 BC'                                                               
________________________________________________________ TestProto.test_proto_codec_error_recovery_02 ________________________________________________________
Traceback (most recent call last):                                                                                                                            
  File "/work/tests/test_proto.py", line 60, in test_proto_codec_error_recovery_02                                                                            
    """)                                                                                                                                                        File "/work/edgedb/blocking_con.py", line 42, in fetchall                                                                                                   
    query, args, kwargs)                                                                                                                                      
  File "edgedb/protocol/blocking_proto.pyx", line 74, in edgedb.protocol.blocking_proto.BlockingIOProtocol.sync_execute_anonymous                             
    return self._iter_coroutine(self.execute_anonymous(*args, **kwargs))       
  File "edgedb/protocol/blocking_proto.pyx", line 60, in edgedb.protocol.blocking_proto.BlockingIOProtocol._iter_coroutine       
    coro.send(None)                                                            
  File "edgedb/protocol/protocol.pyx", line 482, in execute_anonymous                                                                                         
    ret = await self._execute(in_dc, out_dc, args, kwargs)                     
  File "edgedb/protocol/protocol.pyx", line 307, in _execute                                                                                                  
    raise exc                                                                                                                                                 
edgedb.errors.InvalidValueError: invalid input syntax for type std::local_date: '0001-01-01 BC'                                                               
===================================================================== 2 failed in 15.14s =======================
```
Note the error is expected:
```
            with self.assertRaises(edgedb.ClientError):
                # Python dattime.Date object can't represent this date, so
                # we know that the codec will fail.
                # The test will be rewritten once it's possible to override
                # default codecs.
                self.con.fetchall("SELECT <local_date>'0001-01-01 BC';")
```
Just different kind of error. Maybe, something with error hierarchy. Perhaps, it changed recently? (I'm using edgedb from master)

It looks like it's for testing error recovery, so replacing error with `EdgeDBError` might be good enough?

**Comment by 1st1** [comment]
We've reworked out datetime parsing recently (https://github.com/edgedb/edgedb/commit/3e408ab83d44a94fceebe131afe49fe86f6ad6c1) but it appears that we forgot to update edgedb-python tests (automated nightly CI will soon be implemented to prevent situations like this).

This particular test tests an edge case: Python `date` object can't represent some date time ranges. The test insures that the data decoding pipeline handles this exceptional situation correctly and propagates the exception without crippling the protocol state.  Please replace the query with `SELECT to_local_date('0001-01-01 BC');` which should restore the test's original intent.
