### ISSUE TITLE
Pgvector generation failing due to None name

### ISSUE THREAD

**Issue by arunaruljothi** [edgedb/edgedb-python#457]
**Describe the bug**
pgvector in schema has the following type in code generation:
```
ScalarType(desc_id=UUID('297d4ee0-5737-11ee-90a2-ff6fd4e3fb3f'), name=None, base_type=BaseScalarType(desc_id=UUID('9565dd88-04f5-11ee-a691-0b6ebe179825'), name='ext::pgvector::vector'))
```

Which causes this error as the `name` field is empty. 
![Screenshot 2023-09-19 at 6 33 17 PM](https://github.com/edgedb/edgedb-python/assets/62253103/3678d639-e9ac-4f01-a777-c1e6636e8ac0)

**Expected behavior**
No errors should be raised.

**Versions (please complete the following information):**
Happening on latest version of master (with pgvector fix) (ebdac9fa3a41f31866c7cdc112429bec2b2194a0)

Making the following change from this branch fixes this:
https://github.com/arunaruljothi/edgedb-python/tree/fix_None_bug
Using the name_hint here sets the generated object name to the name from the query.

**Comment by fantix** [comment]
What is your EdgeDB server version?

**Comment by arunaruljothi** [comment]
Hi, its on 3.2

Example Schema: 
```
using extension pgvector;

module default {
    scalar type ClipEmbedding extending ext::pgvector::vector<512>;

    type TestObject{
        embedding: ClipEmbedding;
    }
}

```

Example Query:
```
select ext::pgvector::set_probes(10);
select TestObject
order by ext::pgvector::euclidean_distance(.embedding, <ClipEmbedding>$target_embedding)
empty last
limit 1;
```

Then running the codegen command: 
```
edgedb-py -I "stg_db_edgedb" --tls-security insecure --no-skip-pydantic-validation --target blocking --file dist/queries.py
```

Results in:
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ccg-ai-services/bin/edgedb-py", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ccg-ai-services/lib/python3.10/site-packages/edgedb/codegen/cli.py", line 99, in main
    generator.Generator(args).run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ccg-ai-services/lib/python3.10/site-packages/edgedb/codegen/generator.py", line 212, in run
    self._generate_single_file(suffix)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ccg-ai-services/lib/python3.10/site-packages/edgedb/codegen/generator.py", line 263, in _generate_single_file
    output.append(self._generate(name, query, dr))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ccg-ai-services/lib/python3.10/site-packages/edgedb/codegen/generator.py", line 361, in _generate
    args[el_name] = self._generate_code_with_cardinality(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ccg-ai-services/lib/python3.10/site-packages/edgedb/codegen/generator.py", line 548, in _generate_code_with_cardinality
    rv = self._generate_code(type_, name_hint, is_input)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ccg-ai-services/lib/python3.10/site-packages/edgedb/codegen/generator.py", line 456, in _generate_code
    rv = self._find_name(type_.name)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ccg-ai-services/lib/python3.10/site-packages/edgedb/codegen/generator.py", line 561, in _find_name
    if name.startswith(default_prefix):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by fantix** [comment]
Yeah, I can reproduce this now, thanks for the sample.

I believe this is a server bug that the name is not provided when a custom scalar type is only occurring in the input but not the output of the query, but I think your patch is also good as a robustness patch. I'll add a unit test.
