### ISSUE TITLE
Better error for mismatched query parameters and arguments

### ISSUE THREAD

**Issue by dimaqq** [edgedb/edgedb-python#83]
The code like:
```
await c.fetchall("""
    INSERT Foo {
        smth := <str>$smth,
        other := <datetime>$other,
        ...
        # a dozen lines skipped
        ...
        quux := <int16>$quux
    }
""", **some_dict)
```

Fails with:

```
Traceback (most recent call last):
  File "/Users/dima.tisnek/edge/ingest.py", line 47, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/dima.tisnek/edge/ingest.py", line 14, in main
    await c.fetchall("""
  File "/Users/dima.tisnek/Library/Caches/pypoetry/virtualenvs/edge-tfNuXqpZ-py3.9/lib/python3.9/site-packages/edgedb/asyncio_con.py", line 99, in fetchall
    return await self._protocol.execute_anonymous(
  File "edgedb/protocol/protocol.pyx", line 534, in execute_anonymous
  File "edgedb/protocol/protocol.pyx", line 279, in _execute
  File "edgedb/protocol/protocol.pyx", line 987, in edgedb.protocol.protocol.SansIOProtocol.encode_args
  File "edgedb/protocol/./codecs/./namedtuple.pyx", line 74, in edgedb.protocol.protocol.NamedTupleCodec.encode_kwargs
RuntimeError: expected 18 keyword arguments, got 17
```

Clearly the keys in `somedict` don't match the query parameters...

It would be awesome to know which keys :)

**Comment by 1st1** [comment]
Yeah, I agree. Do you want to submit a PR? :)

**Comment by dimaqq** [comment]
+`good first issue`/`help-wanted` label :)

**Comment by nsidnev** [comment]
@1st1, hi! Can I take this?
