### ISSUE TITLE
Not handling `None` arguments correctly

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-python#92]
```
>>> c.fetchone('select <int64>$0 + 1', None)
Traceback (most recent call last):
  File "edgedb/protocol/protocol.pyx", line 409, in edgedb.protocol.protocol.SansIOProtocol._optimistic_execute
  File "edgedb/protocol/protocol.pyx", line 1089, in edgedb.protocol.protocol.SansIOProtocol.parse_data_messages
  File "edgedb/protocol/./codecs/./scalar.pyx", line 31, in edgedb.protocol.protocol.ScalarCodec.decode
  File "edgedb/pgproto/./codecs/int.pyx", line 118, in edgedb.pgproto.pgproto.int8_decode
  File "edgedb/pgproto/./frb.pxd", line 28, in edgedb.pgproto.pgproto.frb_read
  File "edgedb/pgproto/./frb.pyx", line 10, in edgedb.pgproto.pgproto.frb_check
AssertionError: insufficient data in buffer: requested 8 remaining 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yury/dev/venvs/edgedb/lib/python3.8/site-packages/edgedb/blocking_con.py", line 107, in fetchone
    return self._protocol.sync_execute_anonymous(
  File "edgedb/protocol/blocking_proto.pyx", line 91, in edgedb.protocol.blocking_proto.BlockingIOProtocol.sync_execute_anonymous
  File "edgedb/protocol/blocking_proto.pyx", line 77, in edgedb.protocol.blocking_proto.BlockingIOProtocol._iter_coroutine
  File "edgedb/protocol/protocol.pyx", line 555, in execute_anonymous
  File "edgedb/protocol/protocol.pyx", line 445, in _optimistic_execute
edgedb.errors.ClientError: unable to decode data to Python objects
```

**Comment by 1st1** [comment]
@tailhook Paul, could you please take a look if this is still the case?

**Comment by tailhook** [comment]
Yes, this is still the case but this is a problem with the compiler. First, to reproduce the bug we need to change query to `select <OPTIONAL int64>$0 + 1`. And the latter is compiled to:
```

    SELECT/*<pg.SelectStmt at 0x7f783b8e0ac0>*/
            "expr-5~2"."expr~5_serialized~1" AS "expr~5_serialized~2"
        FROM
            LATERAL 
        (SELECT/*<pg.SelectStmt at 0x7f783b8e0bb0>*/
                    ("expr-1~2"."expr~1_value~1" + "expr-3~2"."expr~3_value~1") AS "expr~5_serialized~1"
                FROM
                    LATERAL 
                (SELECT/*<pg.SelectStmt at 0x7f783b8e0fd0>*/
                            ($1)::int8 AS "expr~1_value~1"
                    ) AS "expr-1~2"
                    CROSS JOIN LATERAL 
                (SELECT/*<pg.SelectStmt at 0x7f7839a27280>*/
                            ($2)::int8 AS "expr~3_value~1"
                    ) AS "expr-3~2"
            ) AS "expr-5~2"
        LIMIT 
    (SELECT/*<pg.SelectStmt at 0x7f7839a27730>*/
                (101)::int8 AS "expr~6_value~1"
        )
```
Which yields row with `NULL` instead of zero rows when when first arg is None.

**Comment by elprans** [comment]
This is fixed.
